### PR TITLE
Implement delete many method

### PR DESCRIPTION
**Pull request by ndelvalle**
This PR resolves https://github.com/thedodd/wither/issues/67

### CODE REVIEW

**Review by thedodd — APPROVED** [review]
@ndelvalle thank you for the well-crafted and thoughtful tests! This code looks good, no recommended changes. The one thing that I would ask is that you update the changelog with a line about the additional method.

Once that is done, just ping me and I'll merge and cut a new release. Cheers mate!

**Comment by ndelvalle** [comment]
@thedodd sorry for the delay 😢 I totally forgot about this and ended up using the native driver method in the meanwhile. 
I added the alpha 3 section, not sure if you wanted to do a release.

**Comment by thedodd** [comment]
@ndelvalle no problem. This project definitely needs more love `:)`. Thanks for updating the changelog. Once we merge this, I would be happy to cut a new release.

**Comment by thedodd** [comment]
Done! I just merged your changes + an update merge from master over in #72! So your code is now in master.

**Pull request closed without merging**
